### ISSUE TITLE
class and ClassName at the same time? Please decide

### ISSUE THREAD

**Issue by co0p** [annamarie-now/todo-app-styling#5]
https://github.com/annamarie-now/todo-app-styling/blob/c0c3b14fccfe522bef1df43b9378030f6f97ea97/tailwind/src/App.js#L34

... class is a keyword in javascript and JSX is an extension of javascript. That's the principal reason why React uses className instead of class . Nothing has changed in that regard. Token class denotes that the next token is an identifier and what follows is a class declaration...

**Comment by annamarie-now** [comment]
changed and pushed
